export type Job = {
  id: string;
  title: string;
  company: string;
  city: string;
  salary: string;
  salaryMin: number;
  salaryMax: number;
  mode: string;
  type: string;
  department: string;
  shift: string;
  postedDaysAgo: number;
  experience: string;
  english: string;
  tag: string;
  openings: number;
  location: string;
  interviewAddress: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
};

export const jobs: Job[] = [
  {
    id: "customer-support-executive-821244861",
    title: "Customer Support Executive",
    company: "Aarambh Services",
    city: "Bengaluru/Bangalore",
    salary: "Rs. 18,000 - Rs. 26,000 monthly",
    salaryMin: 18000,
    salaryMax: 26000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Actively hiring",
    openings: 12,
    location: "Koramangala, Bengaluru",
    interviewAddress: "Aarambh Services, 4th Block, Koramangala, Bengaluru",
    description:
      "Aarambh Services is hiring freshers for a customer support role. The job involves helping customers over calls and chat, resolving basic queries, and coordinating with internal teams.",
    responsibilities: [
      "Handle inbound and outbound customer queries professionally.",
      "Maintain daily call records and update customer information.",
      "Coordinate with operations teams for faster query resolution.",
    ],
    requirements: [
      "Freshers can apply with basic computer knowledge.",
      "Comfortable speaking with customers in English and Hindi.",
      "Able to work from office in a day shift.",
    ],
    benefits: ["Paid training", "Performance incentives", "Growth to team lead roles"],
  },
  {
    id: "field-sales-associate-624118305",
    title: "Field Sales Associate",
    company: "Growmore Retail",
    city: "New Delhi",
    salary: "Rs. 20,000 - Rs. 35,000 monthly",
    salaryMin: 20000,
    salaryMax: 35000,
    mode: "Field Job",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Good English",
    tag: "High incentives",
    openings: 8,
    location: "Connaught Place, New Delhi",
    interviewAddress: "Growmore Retail, Connaught Place, New Delhi",
    description:
      "Growmore Retail is looking for energetic sales associates to onboard retailers, explain product offerings, and build strong customer relationships in assigned areas.",
    responsibilities: [
      "Visit assigned markets and generate qualified leads.",
      "Explain pricing, offers, and product benefits to merchants.",
      "Meet daily visit targets and maintain follow-up reports.",
    ],
    requirements: [
      "Freshers and experienced candidates can apply.",
      "Comfortable with local travel and field meetings.",
      "Strong communication and negotiation skills.",
    ],
    benefits: ["Travel allowance", "Attractive incentives", "Fast-track promotion"],
  },
  {
    id: "back-office-executive-420913772",
    title: "Back Office Executive",
    company: "Finline Operations",
    city: "Mumbai/Bombay",
    salary: "Rs. 16,000 - Rs. 24,000 monthly",
    salaryMin: 16000,
    salaryMax: 24000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 5,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Verified",
    openings: 5,
    location: "Andheri East, Mumbai",
    interviewAddress: "Finline Operations, Andheri East, Mumbai",
    description:
      "Finline Operations needs back office executives for data verification, document checks, and daily reporting support for the operations team.",
    responsibilities: [
      "Verify customer records and documents accurately.",
      "Prepare daily MIS and status reports.",
      "Support internal teams with operational follow-ups.",
    ],
    requirements: [
      "Good typing speed and basic MS Excel knowledge.",
      "Attention to detail and willingness to learn.",
      "Freshers can apply.",
    ],
    benefits: ["Fixed day shift", "PF benefits", "Learning support"],
  },
  {
    id: "telecaller-183506294",
    title: "Telecaller",
    company: "Brightpath Solutions",
    city: "Hyderabad",
    salary: "Rs. 15,000 - Rs. 28,000 monthly",
    salaryMin: 15000,
    salaryMax: 28000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Basic English",
    tag: "Immediate joining",
    openings: 10,
    location: "Madhapur, Hyderabad",
    interviewAddress: "Brightpath Solutions, Madhapur, Hyderabad",
    description:
      "Brightpath Solutions is hiring telecallers for lead follow-up, customer assistance, and appointment scheduling for partner businesses.",
    responsibilities: [
      "Call interested customers and explain service details.",
      "Schedule appointments and update call outcomes.",
      "Follow call quality guidelines and daily targets.",
    ],
    requirements: [
      "Clear communication in Hindi or Telugu.",
      "Basic computer knowledge.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Joining bonus", "Monthly incentives", "Friendly team environment"],
  },
  {
    id: "content-moderator-950214688",
    title: "Content Moderator",
    company: "Nextwave Business Services",
    city: "Pune",
    salary: "Rs. 22,000 - Rs. 32,000 monthly",
    salaryMin: 22000,
    salaryMax: 32000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Back Office",
    shift: "Night Shift",
    postedDaysAgo: 6,
    experience: "Freshers only",
    english: "Good English",
    tag: "Night shift",
    openings: 6,
    location: "Viman Nagar, Pune",
    interviewAddress: "Nextwave Business Services, Viman Nagar, Pune",
    description:
      "Nextwave Business Services is hiring content moderators to review digital content, flag policy issues, and support trust and safety workflows.",
    responsibilities: [
      "Review text and image content based on policy guidelines.",
      "Escalate sensitive cases to senior reviewers.",
      "Maintain accuracy and productivity targets.",
    ],
    requirements: [
      "Comfortable working night shifts from office.",
      "Good English reading and comprehension skills.",
      "Freshers can apply.",
    ],
    benefits: ["Night shift allowance", "Cab facility", "Health insurance"],
  },
  {
    id: "delivery-partner-375620194",
    title: "Delivery Partner",
    company: "QuickKart Logistics",
    city: "Chennai",
    salary: "Rs. 25,000 - Rs. 40,000 monthly",
    salaryMin: 25000,
    salaryMax: 40000,
    mode: "Field Job",
    type: "Full Time",
    department: "Delivery",
    shift: "Flexible Shift",
    postedDaysAgo: 8,
    experience: "Any experience",
    english: "No English required",
    tag: "Weekly payout",
    openings: 20,
    location: "T Nagar, Chennai",
    interviewAddress: "QuickKart Logistics hub, T Nagar, Chennai",
    description:
      "QuickKart Logistics is onboarding delivery partners for hyperlocal deliveries with flexible working hours and weekly payout options.",
    responsibilities: [
      "Pick up and deliver orders in assigned areas.",
      "Use the delivery app to update order status.",
      "Follow safety and customer service guidelines.",
    ],
    requirements: [
      "Bike or scooter with valid driving license.",
      "Smartphone with internet access.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Weekly payout", "Flexible shift", "Insurance support"],
  },
  {
    id: "online-tutor-708431256",
    title: "Online Tutor",
    company: "Learnlane Academy",
    city: "Remote",
    salary: "Rs. 12,000 - Rs. 22,000 monthly",
    salaryMin: 12000,
    salaryMax: 22000,
    mode: "Work from Home",
    type: "Part Time",
    department: "Customer Support",
    shift: "Evening Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 4,
    location: "Work from home",
    interviewAddress: "Online interview",
    description:
      "Learnlane Academy is hiring online tutors to support school students with guided practice sessions and doubt resolution from home.",
    responsibilities: [
      "Conduct online learning sessions in the evening.",
      "Help students revise concepts and solve doubts.",
      "Share session feedback with academic coordinators.",
    ],
    requirements: [
      "Good English communication and subject clarity.",
      "Laptop or desktop with stable internet.",
      "Freshers with teaching interest can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "Teaching certificate"],
  },
  {
    id: "marketing-intern-514907223",
    title: "Marketing Intern",
    company: "Launchpad Brands",
    city: "Gurugram",
    salary: "Rs. 10,000 - Rs. 18,000 monthly",
    salaryMin: 10000,
    salaryMax: 18000,
    mode: "Work from Office",
    type: "Internship",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Internship",
    openings: 3,
    location: "Sector 44, Gurugram",
    interviewAddress: "Launchpad Brands, Sector 44, Gurugram",
    description:
      "Launchpad Brands is offering a marketing internship for freshers who want hands-on exposure to campaigns, lead generation, and brand activations.",
    responsibilities: [
      "Assist with marketing campaigns and lead research.",
      "Coordinate with sales teams for campaign follow-ups.",
      "Prepare simple reports on campaign performance.",
    ],
    requirements: [
      "Basic communication and spreadsheet skills.",
      "Interest in sales, marketing, or brand management.",
      "Available for full internship duration.",
    ],
    benefits: ["Internship certificate", "Pre-placement opportunity", "Mentorship"],
  },
  // Work from Home Jobs
  {
    id: "remote-customer-support-612345001",
    title: "Remote Customer Support Executive",
    company: "HelpDesk India",
    city: "Remote",
    salary: "Rs. 18,000 - Rs. 28,000 monthly",
    salaryMin: 18000,
    salaryMax: 28000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Good English",
    tag: "Actively hiring",
    openings: 15,
    location: "Work from home",
    interviewAddress: "Online interview via video call",
    description:
      "HelpDesk India is hiring remote customer support executives to handle customer queries over chat and email. Work fully from home with flexible timings.",
    responsibilities: [
      "Respond to customer queries via chat and email promptly.",
      "Resolve complaints and escalate unresolved issues to senior agents.",
      "Maintain accurate records of customer interactions.",
    ],
    requirements: [
      "Laptop or desktop with stable internet connection.",
      "Good written English communication skills.",
      "Freshers with basic computer knowledge can apply.",
    ],
    benefits: ["Work from home", "Internet allowance", "Performance bonuses"],
  },
  {
    id: "wfh-data-entry-operator-612345002",
    title: "Data Entry Operator",
    company: "Databridge Solutions",
    city: "Remote",
    salary: "Rs. 12,000 - Rs. 20,000 monthly",
    salaryMin: 12000,
    salaryMax: 20000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Remote",
    openings: 20,
    location: "Work from home",
    interviewAddress: "Online interview",
    description:
      "Databridge Solutions is looking for data entry operators to work remotely. The role involves entering and verifying data in company systems with accuracy.",
    responsibilities: [
      "Enter data from source documents into the company database.",
      "Verify and correct data discrepancies.",
      "Generate daily reports and share with the team lead.",
    ],
    requirements: [
      "Typing speed of at least 30 WPM.",
      "Basic MS Excel and MS Word knowledge.",
      "Freshers can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "Monthly incentives"],
  },
  {
    id: "wfh-telecaller-612345003",
    title: "Telecaller (Work from Home)",
    company: "ConnectFirst BPO",
    city: "Remote",
    salary: "Rs. 15,000 - Rs. 25,000 monthly",
    salaryMin: 15000,
    salaryMax: 25000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Basic English",
    tag: "Immediate joining",
    openings: 30,
    location: "Work from home",
    interviewAddress: "Online interview via phone",
    description:
      "ConnectFirst BPO is hiring telecallers to work from home. You will be making outbound calls to potential customers and explaining product offerings.",
    responsibilities: [
      "Make outbound calls to prospective customers from home.",
      "Explain product features and handle basic objections.",
      "Update call logs and daily reports in the CRM system.",
    ],
    requirements: [
      "Clear verbal communication in Hindi or English.",
      "Smartphone or landline with stable connectivity.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Work from home", "Joining bonus", "Incentives on targets"],
  },
  {
    id: "wfh-content-writer-612345004",
    title: "Content Writer",
    company: "Wordcraft Media",
    city: "Remote",
    salary: "Rs. 20,000 - Rs. 35,000 monthly",
    salaryMin: 20000,
    salaryMax: 35000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 3,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 5,
    location: "Work from home",
    interviewAddress: "Online interview",
    description:
      "Wordcraft Media is looking for creative content writers to produce blog posts, product descriptions, and social media content from home.",
    responsibilities: [
      "Write SEO-friendly articles and blog posts on assigned topics.",
      "Edit and proofread content before submission.",
      "Collaborate with the editorial team via online tools.",
    ],
    requirements: [
      "Strong written English skills.",
      "Laptop with internet and basic research ability.",
      "Freshers with a portfolio or writing samples preferred.",
    ],
    benefits: ["Work from home", "Flexible hours", "Skill development"],
  },
  {
    id: "wfh-accountant-612345005",
    title: "Accounts Executive (Remote)",
    company: "Finserve Consultants",
    city: "Remote",
    salary: "Rs. 22,000 - Rs. 38,000 monthly",
    salaryMin: 22000,
    salaryMax: 38000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Accounts / Finance",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Good English",
    tag: "Verified",
    openings: 4,
    location: "Work from home",
    interviewAddress: "Online interview via video call",
    description:
      "Finserve Consultants is hiring remote accounts executives to manage bookkeeping, invoicing, and financial reporting for client accounts.",
    responsibilities: [
      "Maintain books of accounts using Tally or similar software.",
      "Prepare and send invoices to clients.",
      "Assist in monthly financial reporting and reconciliation.",
    ],
    requirements: [
      "B.Com or equivalent qualification.",
      "Knowledge of Tally ERP or similar accounting software.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Work from home", "PF benefits", "Annual appraisal"],
  },
  {
    id: "wfh-social-media-executive-612345006",
    title: "Social Media Executive",
    company: "BrandBuzz Digital",
    city: "Remote",
    salary: "Rs. 18,000 - Rs. 30,000 monthly",
    salaryMin: 18000,
    salaryMax: 30000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 6,
    location: "Work from home",
    interviewAddress: "Online interview",
    description:
      "BrandBuzz Digital is hiring social media executives to manage brand pages, create engaging posts, and grow follower communities from home.",
    responsibilities: [
      "Create and schedule posts across Instagram, Facebook, and LinkedIn.",
      "Respond to comments and messages on brand pages.",
      "Track engagement metrics and prepare weekly reports.",
    ],
    requirements: [
      "Familiarity with social media platforms and basic design tools.",
      "Good written communication in English.",
      "Freshers with a creative mindset can apply.",
    ],
    benefits: ["Work from home", "Creative work environment", "Growth opportunities"],
  },
  {
    id: "wfh-hr-recruiter-612345007",
    title: "HR Recruiter (Work from Home)",
    company: "TalentBridge HR",
    city: "Remote",
    salary: "Rs. 15,000 - Rs. 25,000 monthly",
    salaryMin: 15000,
    salaryMax: 25000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Human Resource",
    shift: "Day Shift",
    postedDaysAgo: 5,
    experience: "Freshers only",
    english: "Good English",
    tag: "Actively hiring",
    openings: 8,
    location: "Work from home",
    interviewAddress: "Online interview",
    description:
      "TalentBridge HR is looking for remote HR recruiters to source candidates, conduct initial screening calls, and coordinate interview schedules.",
    responsibilities: [
      "Source candidates through job portals and social media.",
      "Conduct telephonic screening interviews.",
      "Coordinate with hiring managers and schedule interviews.",
    ],
    requirements: [
      "Good communication and interpersonal skills.",
      "Laptop with internet access.",
      "Freshers with an interest in HR can apply.",
    ],
    benefits: ["Work from home", "Incentives on closures", "Learning and development"],
  },
  {
    id: "wfh-graphic-designer-612345008",
    title: "Graphic Designer (Remote)",
    company: "Pixel Studio",
    city: "Remote",
    salary: "Rs. 20,000 - Rs. 40,000 monthly",
    salaryMin: 20000,
    salaryMax: 40000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Basic English",
    tag: "Remote",
    openings: 3,
    location: "Work from home",
    interviewAddress: "Online portfolio review",
    description:
      "Pixel Studio is hiring remote graphic designers to create visual content for digital campaigns, social media, and client presentations.",
    responsibilities: [
      "Design banners, social media creatives, and marketing materials.",
      "Work with the content team to align visuals with brand guidelines.",
      "Deliver projects on time with revisions as needed.",
    ],
    requirements: [
      "Proficiency in Adobe Photoshop, Illustrator, or Canva.",
      "Portfolio of design work required.",
      "Freshers and experienced designers can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "Creative freedom"],
  },
  // --- More Office / Field Jobs ---
  {
    id: "sales-executive-jaipur-730001001",
    title: "Sales Executive",
    company: "Rajputana Distributors",
    city: "Jaipur",
    salary: "Rs. 18,000 - Rs. 32,000 monthly",
    salaryMin: 18000,
    salaryMax: 32000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Basic English",
    tag: "Actively hiring",
    openings: 14,
    location: "Malviya Nagar, Jaipur",
    interviewAddress: "Rajputana Distributors, Malviya Nagar, Jaipur",
    description: "Rajputana Distributors is expanding its sales team and looking for motivated sales executives to drive product sales across Jaipur and nearby areas.",
    responsibilities: [
      "Visit retail outlets and generate new business leads.",
      "Achieve monthly sales targets and maintain client relationships.",
      "Submit daily sales reports to the area manager.",
    ],
    requirements: [
      "Two-wheeler preferred for field visits.",
      "Basic communication skills in Hindi.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Travel allowance", "Monthly incentives", "Promotion opportunities"],
  },
  {
    id: "warehouse-associate-pune-730001002",
    title: "Warehouse Associate",
    company: "StoreSmart Logistics",
    city: "Pune",
    salary: "Rs. 14,000 - Rs. 22,000 monthly",
    salaryMin: 14000,
    salaryMax: 22000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Delivery",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "No English required",
    tag: "Immediate joining",
    openings: 25,
    location: "Chakan, Pune",
    interviewAddress: "StoreSmart Logistics, Chakan Industrial Area, Pune",
    description: "StoreSmart Logistics needs warehouse associates for inbound and outbound operations at their Chakan facility.",
    responsibilities: [
      "Receive, sort, and store incoming inventory.",
      "Pick and pack orders as per dispatch schedule.",
      "Maintain cleanliness and safety in the warehouse.",
    ],
    requirements: [
      "Physically fit and comfortable with manual work.",
      "Willing to work in shifts.",
      "No prior experience required.",
    ],
    benefits: ["PF and ESI", "Overtime pay", "Canteen facility"],
  },
  {
    id: "receptionist-kolkata-730001003",
    title: "Receptionist",
    company: "Meridian Clinics",
    city: "Kolkata/Calcutta",
    salary: "Rs. 12,000 - Rs. 18,000 monthly",
    salaryMin: 12000,
    salaryMax: 18000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Freshers only",
    english: "Good English",
    tag: "Verified",
    openings: 2,
    location: "Salt Lake, Kolkata",
    interviewAddress: "Meridian Clinics, Sector V, Salt Lake, Kolkata",
    description: "Meridian Clinics is hiring a receptionist to manage front desk operations, patient appointments, and general administrative tasks.",
    responsibilities: [
      "Greet patients and manage appointment scheduling.",
      "Handle phone calls and direct queries to the right department.",
      "Maintain patient records and front desk registers.",
    ],
    requirements: [
      "Pleasant personality and good communication skills.",
      "Basic computer knowledge.",
      "Freshers can apply.",
    ],
    benefits: ["Fixed salary", "Medical benefits", "Friendly work environment"],
  },
  {
    id: "security-guard-ahmedabad-730001004",
    title: "Security Guard",
    company: "ShieldForce Security",
    city: "Ahmedabad",
    salary: "Rs. 12,000 - Rs. 16,000 monthly",
    salaryMin: 12000,
    salaryMax: 16000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Back Office",
    shift: "Night Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "No English required",
    tag: "Immediate joining",
    openings: 18,
    location: "Naroda, Ahmedabad",
    interviewAddress: "ShieldForce Security, Naroda Industrial Area, Ahmedabad",
    description: "ShieldForce Security is hiring security guards for industrial and commercial premises across Ahmedabad.",
    responsibilities: [
      "Monitor entry and exit of personnel and vehicles.",
      "Conduct regular rounds of the premises.",
      "Report any suspicious activity to the supervisor.",
    ],
    requirements: [
      "Minimum 10th pass.",
      "Physically fit with no criminal record.",
      "Ex-servicemen preferred but not mandatory.",
    ],
    benefits: ["Uniform provided", "PF and ESI", "Night shift allowance"],
  },
  {
    id: "cook-restaurant-mumbai-730001005",
    title: "Cook / Chef",
    company: "Spice Garden Restaurants",
    city: "Mumbai/Bombay",
    salary: "Rs. 18,000 - Rs. 30,000 monthly",
    salaryMin: 18000,
    salaryMax: 30000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Restaurant / Hospitality",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "No English required",
    tag: "Actively hiring",
    openings: 7,
    location: "Bandra West, Mumbai",
    interviewAddress: "Spice Garden Restaurants, Bandra West, Mumbai",
    description: "Spice Garden Restaurants is looking for experienced cooks and chefs to join their kitchen team at their Bandra outlet.",
    responsibilities: [
      "Prepare Indian and continental dishes as per the menu.",
      "Maintain hygiene and food safety standards in the kitchen.",
      "Assist in inventory management and ingredient preparation.",
    ],
    requirements: [
      "Minimum 1 year of cooking experience preferred.",
      "Knowledge of Indian cuisine is mandatory.",
      "Freshers with culinary training can also apply.",
    ],
    benefits: ["Meals provided", "Tips sharing", "Festival bonuses"],
  },
  {
    id: "hr-executive-chennai-730001006",
    title: "HR Executive",
    company: "Nexgen Staffing",
    city: "Chennai",
    salary: "Rs. 20,000 - Rs. 32,000 monthly",
    salaryMin: 20000,
    salaryMax: 32000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Human Resource",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Any experience",
    english: "Good English",
    tag: "Verified",
    openings: 3,
    location: "Anna Nagar, Chennai",
    interviewAddress: "Nexgen Staffing, Anna Nagar, Chennai",
    description: "Nexgen Staffing is hiring HR executives to manage end-to-end recruitment, onboarding, and employee engagement activities.",
    responsibilities: [
      "Post job openings and screen incoming applications.",
      "Coordinate interviews and manage offer letter processes.",
      "Handle employee onboarding and maintain HR records.",
    ],
    requirements: [
      "MBA in HR or equivalent qualification preferred.",
      "Good communication and organizational skills.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Health insurance", "Annual bonus", "Learning budget"],
  },
  {
    id: "accounts-assistant-lucknow-730001007",
    title: "Accounts Assistant",
    company: "Awadh Finance Services",
    city: "Lucknow",
    salary: "Rs. 14,000 - Rs. 22,000 monthly",
    salaryMin: 14000,
    salaryMax: 22000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Accounts / Finance",
    shift: "Day Shift",
    postedDaysAgo: 5,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Verified",
    openings: 4,
    location: "Hazratganj, Lucknow",
    interviewAddress: "Awadh Finance Services, Hazratganj, Lucknow",
    description: "Awadh Finance Services is hiring accounts assistants to support daily bookkeeping, billing, and financial documentation tasks.",
    responsibilities: [
      "Assist in maintaining daily accounts and ledgers.",
      "Prepare GST invoices and manage petty cash.",
      "Support the senior accountant with monthly closing.",
    ],
    requirements: [
      "B.Com or equivalent degree.",
      "Basic Tally knowledge is a plus.",
      "Freshers can apply.",
    ],
    benefits: ["Fixed salary", "PF benefits", "On-the-job training"],
  },
  {
    id: "bpo-agent-hyderabad-730001008",
    title: "BPO Customer Care Agent",
    company: "VoiceConnect BPO",
    city: "Hyderabad",
    salary: "Rs. 16,000 - Rs. 26,000 monthly",
    salaryMin: 16000,
    salaryMax: 26000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Customer Support",
    shift: "Night Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Good English",
    tag: "Night shift",
    openings: 22,
    location: "Gachibowli, Hyderabad",
    interviewAddress: "VoiceConnect BPO, Gachibowli, Hyderabad",
    description: "VoiceConnect BPO is hiring customer care agents for international voice process. Night shift with cab facility.",
    responsibilities: [
      "Handle inbound calls from international customers.",
      "Resolve queries related to billing, accounts, and services.",
      "Maintain call quality and meet CSAT targets.",
    ],
    requirements: [
      "Fluent spoken English is mandatory.",
      "Comfortable working night shifts.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Night shift allowance", "Cab facility", "Health insurance"],
  },
  {
    id: "delivery-executive-delhi-730001009",
    title: "Delivery Executive",
    company: "ZoomRush Delivery",
    city: "New Delhi",
    salary: "Rs. 20,000 - Rs. 35,000 monthly",
    salaryMin: 20000,
    salaryMax: 35000,
    mode: "Field Job",
    type: "Full Time",
    department: "Delivery",
    shift: "Flexible Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "No English required",
    tag: "Weekly payout",
    openings: 40,
    location: "Dwarka, New Delhi",
    interviewAddress: "ZoomRush Delivery Hub, Dwarka Sector 10, New Delhi",
    description: "ZoomRush Delivery is onboarding delivery executives for last-mile delivery across Delhi NCR. Flexible hours and weekly payouts.",
    responsibilities: [
      "Pick up parcels from the hub and deliver to customers.",
      "Update delivery status on the app in real time.",
      "Handle cash-on-delivery collections responsibly.",
    ],
    requirements: [
      "Valid two-wheeler driving license.",
      "Android smartphone with internet.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Weekly payout", "Fuel allowance", "Accident insurance"],
  },
  {
    id: "retail-sales-bangalore-730001010",
    title: "Retail Sales Associate",
    company: "TrendZone Fashion",
    city: "Bengaluru/Bangalore",
    salary: "Rs. 15,000 - Rs. 24,000 monthly",
    salaryMin: 15000,
    salaryMax: 24000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Retail / Counter Sales",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Basic English",
    tag: "Actively hiring",
    openings: 10,
    location: "Indiranagar, Bengaluru",
    interviewAddress: "TrendZone Fashion, 100 Feet Road, Indiranagar, Bengaluru",
    description: "TrendZone Fashion is hiring retail sales associates for their Indiranagar store. The role involves assisting customers, managing stock, and driving in-store sales.",
    responsibilities: [
      "Assist customers in selecting products and completing purchases.",
      "Maintain store display and ensure shelves are stocked.",
      "Handle billing and cash management at the counter.",
    ],
    requirements: [
      "Good interpersonal skills and a customer-first attitude.",
      "Comfortable standing for extended periods.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Staff discount", "Sales incentives", "Uniform provided"],
  },
  {
    id: "field-collection-agent-indore-730001011",
    title: "Field Collection Agent",
    company: "Madhya Finance Corp",
    city: "Indore",
    salary: "Rs. 16,000 - Rs. 28,000 monthly",
    salaryMin: 16000,
    salaryMax: 28000,
    mode: "Field Job",
    type: "Full Time",
    department: "Accounts / Finance",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Basic English",
    tag: "High incentives",
    openings: 12,
    location: "Vijay Nagar, Indore",
    interviewAddress: "Madhya Finance Corp, Vijay Nagar, Indore",
    description: "Madhya Finance Corp is hiring field collection agents to visit customers, collect EMI payments, and maintain collection records.",
    responsibilities: [
      "Visit assigned customers and collect overdue EMI payments.",
      "Maintain daily collection reports and deposit cash.",
      "Coordinate with the branch office for escalations.",
    ],
    requirements: [
      "Two-wheeler with valid license.",
      "Good communication in Hindi.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Travel allowance", "Collection incentives", "PF benefits"],
  },
  {
    id: "data-analyst-intern-gurugram-730001012",
    title: "Data Analyst Intern",
    company: "InsightEdge Analytics",
    city: "Gurugram",
    salary: "Rs. 12,000 - Rs. 20,000 monthly",
    salaryMin: 12000,
    salaryMax: 20000,
    mode: "Work from Office",
    type: "Internship",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Freshers only",
    english: "Good English",
    tag: "Internship",
    openings: 5,
    location: "Cyber City, Gurugram",
    interviewAddress: "InsightEdge Analytics, DLF Cyber City, Gurugram",
    description: "InsightEdge Analytics is offering a data analyst internship for freshers who want to build skills in Excel, SQL, and data visualization.",
    responsibilities: [
      "Assist in cleaning and organizing datasets.",
      "Create dashboards and reports using Excel or Power BI.",
      "Support the analytics team with ad-hoc data requests.",
    ],
    requirements: [
      "Basic knowledge of MS Excel and data handling.",
      "Interest in data analysis and reporting.",
      "Freshers pursuing or having completed graduation can apply.",
    ],
    benefits: ["Internship certificate", "Pre-placement offer possibility", "Mentorship"],
  },
  // --- More Work from Home Jobs ---
  {
    id: "wfh-virtual-assistant-730002001",
    title: "Virtual Assistant",
    company: "RemoteDesk Services",
    city: "Remote",
    salary: "Rs. 15,000 - Rs. 25,000 monthly",
    salaryMin: 15000,
    salaryMax: 25000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 10,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "RemoteDesk Services is hiring virtual assistants to support clients with scheduling, email management, research, and administrative tasks from home.",
    responsibilities: [
      "Manage client calendars and schedule meetings.",
      "Handle email correspondence and draft responses.",
      "Conduct online research and compile reports.",
    ],
    requirements: [
      "Good written and spoken English.",
      "Laptop with stable internet and MS Office knowledge.",
      "Freshers with strong organizational skills can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "International client exposure"],
  },
  {
    id: "wfh-online-sales-executive-730002002",
    title: "Online Sales Executive",
    company: "ShopNow Commerce",
    city: "Remote",
    salary: "Rs. 18,000 - Rs. 32,000 monthly",
    salaryMin: 18000,
    salaryMax: 32000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Good English",
    tag: "High incentives",
    openings: 20,
    location: "Work from home",
    interviewAddress: "Online interview via video call",
    description: "ShopNow Commerce is hiring online sales executives to reach out to potential customers, demonstrate products via video calls, and close sales remotely.",
    responsibilities: [
      "Contact leads via phone and video calls to pitch products.",
      "Follow up on inquiries and convert them into sales.",
      "Maintain CRM records and daily sales reports.",
    ],
    requirements: [
      "Good communication and persuasion skills.",
      "Laptop with internet and a quiet workspace.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Work from home", "High incentives on sales", "Monthly top performer awards"],
  },
  {
    id: "wfh-proofreader-730002003",
    title: "Proofreader / Editor",
    company: "CleanCopy Editorial",
    city: "Remote",
    salary: "Rs. 16,000 - Rs. 28,000 monthly",
    salaryMin: 16000,
    salaryMax: 28000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 3,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 4,
    location: "Work from home",
    interviewAddress: "Online test and interview",
    description: "CleanCopy Editorial is hiring remote proofreaders and editors to review articles, marketing copy, and academic content for grammar, clarity, and style.",
    responsibilities: [
      "Proofread and edit content for grammar and spelling errors.",
      "Ensure consistency in tone, style, and formatting.",
      "Return corrected documents within agreed deadlines.",
    ],
    requirements: [
      "Excellent command of written English.",
      "Attention to detail and ability to meet deadlines.",
      "Freshers with strong language skills can apply.",
    ],
    benefits: ["Work from home", "Flexible schedule", "Skill development"],
  },
  {
    id: "wfh-python-developer-intern-730002004",
    title: "Python Developer Intern",
    company: "CodeNest Technologies",
    city: "Remote",
    salary: "Rs. 10,000 - Rs. 20,000 monthly",
    salaryMin: 10000,
    salaryMax: 20000,
    mode: "Work from Home",
    type: "Internship",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 2,
    experience: "Freshers only",
    english: "Good English",
    tag: "Internship",
    openings: 6,
    location: "Work from home",
    interviewAddress: "Online coding test and interview",
    description: "CodeNest Technologies is offering a remote Python developer internship for students and freshers who want to build real-world coding experience.",
    responsibilities: [
      "Write and test Python scripts for automation and data tasks.",
      "Assist senior developers with feature development.",
      "Document code and participate in code reviews.",
    ],
    requirements: [
      "Basic Python programming knowledge.",
      "Laptop with internet and a code editor.",
      "Freshers and final-year students can apply.",
    ],
    benefits: ["Work from home", "Internship certificate", "Pre-placement opportunity"],
  },
  {
    id: "wfh-insurance-advisor-730002005",
    title: "Insurance Advisor (Remote)",
    company: "SecureLife Insurance",
    city: "Remote",
    salary: "Rs. 15,000 - Rs. 40,000 monthly",
    salaryMin: 15000,
    salaryMax: 40000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Flexible Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Basic English",
    tag: "High incentives",
    openings: 50,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "SecureLife Insurance is hiring remote insurance advisors to counsel customers on life and health insurance plans and help them choose the right coverage.",
    responsibilities: [
      "Call assigned leads and explain insurance products.",
      "Help customers select suitable plans and complete documentation.",
      "Meet monthly policy issuance targets.",
    ],
    requirements: [
      "Good communication skills in Hindi or regional language.",
      "Smartphone with internet access.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Work from home", "Unlimited earning potential", "IRDA certification support"],
  },
  {
    id: "wfh-medical-transcriptionist-730002006",
    title: "Medical Transcriptionist",
    company: "HealthScript Services",
    city: "Remote",
    salary: "Rs. 18,000 - Rs. 30,000 monthly",
    salaryMin: 18000,
    salaryMax: 30000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Any experience",
    english: "Good English",
    tag: "Remote",
    openings: 8,
    location: "Work from home",
    interviewAddress: "Online typing test and interview",
    description: "HealthScript Services is hiring remote medical transcriptionists to convert audio recordings from healthcare professionals into accurate written reports.",
    responsibilities: [
      "Transcribe physician dictations into medical reports.",
      "Review and edit transcribed content for accuracy.",
      "Maintain confidentiality of patient information.",
    ],
    requirements: [
      "Typing speed of at least 50 WPM.",
      "Knowledge of medical terminology preferred.",
      "Freshers with medical transcription training can apply.",
    ],
    benefits: ["Work from home", "Productivity bonuses", "Flexible hours"],
  },
  {
    id: "wfh-digital-marketing-exec-730002007",
    title: "Digital Marketing Executive",
    company: "GrowthPulse Digital",
    city: "Remote",
    salary: "Rs. 20,000 - Rs. 35,000 monthly",
    salaryMin: 20000,
    salaryMax: 35000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Sales & BD",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Good English",
    tag: "Remote",
    openings: 5,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "GrowthPulse Digital is hiring remote digital marketing executives to plan and execute SEO, paid ads, and email marketing campaigns for clients.",
    responsibilities: [
      "Manage Google Ads and Meta Ads campaigns.",
      "Optimize website content for SEO performance.",
      "Prepare weekly performance reports for clients.",
    ],
    requirements: [
      "Knowledge of Google Ads, Meta Ads, or SEO tools.",
      "Laptop with internet access.",
      "Freshers with digital marketing certifications can apply.",
    ],
    benefits: ["Work from home", "Skill development budget", "Performance bonuses"],
  },
  {
    id: "wfh-customer-retention-730002008",
    title: "Customer Retention Specialist",
    company: "RetainPro Solutions",
    city: "Remote",
    salary: "Rs. 20,000 - Rs. 32,000 monthly",
    salaryMin: 20000,
    salaryMax: 32000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Good English",
    tag: "Actively hiring",
    openings: 12,
    location: "Work from home",
    interviewAddress: "Online interview via video call",
    description: "RetainPro Solutions is hiring remote customer retention specialists to engage with at-risk customers, resolve concerns, and reduce churn for subscription-based clients.",
    responsibilities: [
      "Contact customers who have cancelled or are about to cancel subscriptions.",
      "Understand their concerns and offer suitable solutions or offers.",
      "Log all interactions in the CRM and report daily outcomes.",
    ],
    requirements: [
      "Strong empathy and negotiation skills.",
      "Laptop with stable internet.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Work from home", "Retention bonuses", "Career growth"],
  },
  {
    id: "wfh-tally-operator-730002009",
    title: "Tally Operator (Work from Home)",
    company: "QuickBooks Outsourcing",
    city: "Remote",
    salary: "Rs. 14,000 - Rs. 22,000 monthly",
    salaryMin: 14000,
    salaryMax: 22000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Accounts / Finance",
    shift: "Day Shift",
    postedDaysAgo: 5,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Remote",
    openings: 9,
    location: "Work from home",
    interviewAddress: "Online Tally test and interview",
    description: "QuickBooks Outsourcing is hiring remote Tally operators to handle accounting entries, GST filing support, and financial data management for small business clients.",
    responsibilities: [
      "Enter purchase, sales, and journal vouchers in Tally.",
      "Reconcile bank statements and ledger accounts.",
      "Assist in GST return preparation.",
    ],
    requirements: [
      "Proficiency in Tally ERP 9 or Tally Prime.",
      "Laptop with Tally software installed.",
      "Freshers with Tally certification can apply.",
    ],
    benefits: ["Work from home", "Fixed salary", "Skill enhancement"],
  },
  {
    id: "wfh-research-analyst-730002010",
    title: "Research Analyst (Remote)",
    company: "DataMind Research",
    city: "Remote",
    salary: "Rs. 22,000 - Rs. 40,000 monthly",
    salaryMin: 22000,
    salaryMax: 40000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Good English",
    tag: "Verified",
    openings: 4,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "DataMind Research is hiring remote research analysts to gather, analyze, and present market and industry data for client reports.",
    responsibilities: [
      "Conduct secondary research using online databases and reports.",
      "Analyze data and identify key trends and insights.",
      "Prepare structured research reports and presentations.",
    ],
    requirements: [
      "Strong analytical and report-writing skills.",
      "Proficiency in MS Excel and PowerPoint.",
      "Freshers with a research background can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "Exposure to diverse industries"],
  },  // --- Part Time Jobs ---
  {
    id: "part-time-cashier-bangalore-840001001",
    title: "Part Time Cashier",
    company: "FreshMart Superstore",
    city: "Bengaluru/Bangalore",
    salary: "Rs. 8,000 - Rs. 12,000 monthly",
    salaryMin: 8000,
    salaryMax: 12000,
    mode: "Work from Office",
    type: "Part Time",
    department: "Retail / Counter Sales",
    shift: "Evening Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Basic English",
    tag: "Part time",
    openings: 8,
    location: "Koramangala, Bengaluru",
    interviewAddress: "FreshMart Superstore, Koramangala, Bengaluru",
    description: "FreshMart Superstore is hiring part-time cashiers for evening shifts. Ideal for students or homemakers looking for flexible work.",
    responsibilities: [
      "Handle billing and cash/card transactions at the counter.",
      "Assist customers with queries and product locations.",
      "Maintain cleanliness and order at the checkout area.",
    ],
    requirements: [
      "Basic math and computer skills.",
      "Comfortable working evening shifts.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Flexible hours", "Staff discount", "Weekly payout"],
  },
  {
    id: "part-time-delivery-mumbai-840001002",
    title: "Part Time Delivery Boy",
    company: "SwiftBite Food Delivery",
    city: "Mumbai/Bombay",
    salary: "Rs. 10,000 - Rs. 18,000 monthly",
    salaryMin: 10000,
    salaryMax: 18000,
    mode: "Field Job",
    type: "Part Time",
    department: "Delivery",
    shift: "Evening Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "No English required",
    tag: "Flexible hours",
    openings: 30,
    location: "Andheri, Mumbai",
    interviewAddress: "SwiftBite Hub, Andheri West, Mumbai",
    description: "SwiftBite Food Delivery is hiring part-time delivery partners for evening and weekend slots across Mumbai.",
    responsibilities: [
      "Pick up food orders from restaurants and deliver to customers.",
      "Update delivery status on the app.",
      "Handle cash-on-delivery payments responsibly.",
    ],
    requirements: [
      "Two-wheeler with valid driving license.",
      "Smartphone with internet.",
      "Available for evening or weekend shifts.",
    ],
    benefits: ["Per-delivery earnings", "Flexible schedule", "Weekly payout"],
  },
  {
    id: "part-time-data-entry-delhi-840001003",
    title: "Part Time Data Entry Operator",
    company: "Infotrack Systems",
    city: "New Delhi",
    salary: "Rs. 7,000 - Rs. 12,000 monthly",
    salaryMin: 7000,
    salaryMax: 12000,
    mode: "Work from Office",
    type: "Part Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Part time",
    openings: 10,
    location: "Laxmi Nagar, New Delhi",
    interviewAddress: "Infotrack Systems, Laxmi Nagar, New Delhi",
    description: "Infotrack Systems is hiring part-time data entry operators for morning shifts. Suitable for students and homemakers.",
    responsibilities: [
      "Enter data from physical documents into the system.",
      "Verify entries for accuracy.",
      "Submit daily work reports to the supervisor.",
    ],
    requirements: [
      "Typing speed of at least 25 WPM.",
      "Basic MS Office knowledge.",
      "Freshers can apply.",
    ],
    benefits: ["Fixed part-time salary", "Morning shift", "Learning opportunity"],
  },
  {
    id: "part-time-telecaller-hyderabad-840001004",
    title: "Part Time Telecaller",
    company: "QuickCall Services",
    city: "Hyderabad",
    salary: "Rs. 8,000 - Rs. 14,000 monthly",
    salaryMin: 8000,
    salaryMax: 14000,
    mode: "Work from Office",
    type: "Part Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Basic English",
    tag: "Part time",
    openings: 15,
    location: "Ameerpet, Hyderabad",
    interviewAddress: "QuickCall Services, Ameerpet, Hyderabad",
    description: "QuickCall Services is hiring part-time telecallers for 4-hour morning shifts. Ideal for students and homemakers.",
    responsibilities: [
      "Make outbound calls to leads and explain service offerings.",
      "Record call outcomes in the CRM.",
      "Meet daily call targets.",
    ],
    requirements: [
      "Clear communication in Telugu or Hindi.",
      "Basic computer knowledge.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Part-time salary", "Incentives on targets", "Friendly environment"],
  },
  {
    id: "part-time-wfh-content-840001005",
    title: "Part Time Content Writer (WFH)",
    company: "Inkwell Digital",
    city: "Remote",
    salary: "Rs. 8,000 - Rs. 15,000 monthly",
    salaryMin: 8000,
    salaryMax: 15000,
    mode: "Work from Home",
    type: "Part Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 3,
    experience: "Freshers only",
    english: "Good English",
    tag: "Remote",
    openings: 6,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "Inkwell Digital is hiring part-time content writers to produce 2-3 articles per week from home. Great for students and freelancers.",
    responsibilities: [
      "Write blog posts and articles on assigned topics.",
      "Submit work by agreed deadlines.",
      "Incorporate feedback from editors.",
    ],
    requirements: [
      "Good written English.",
      "Laptop with internet.",
      "Freshers with writing interest can apply.",
    ],
    benefits: ["Work from home", "Flexible hours", "Per-article payment option"],
  },
  {
    id: "part-time-tutor-pune-840001006",
    title: "Part Time Home Tutor",
    company: "BrightMinds Tutoring",
    city: "Pune",
    salary: "Rs. 10,000 - Rs. 20,000 monthly",
    salaryMin: 10000,
    salaryMax: 20000,
    mode: "Field Job",
    type: "Part Time",
    department: "Customer Support",
    shift: "Evening Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Good English",
    tag: "Part time",
    openings: 12,
    location: "Kothrud, Pune",
    interviewAddress: "BrightMinds Tutoring, Kothrud, Pune",
    description: "BrightMinds Tutoring is looking for part-time home tutors for school students in Pune. Evening slots available.",
    responsibilities: [
      "Teach assigned subjects to school students at their homes.",
      "Prepare students for exams and tests.",
      "Provide progress updates to parents.",
    ],
    requirements: [
      "Graduate in relevant subject.",
      "Good communication and patience.",
      "Freshers and experienced tutors can apply.",
    ],
    benefits: ["Flexible schedule", "Good pay per hour", "Teaching experience"],
  },
  // --- Jobs for Women ---
  {
    id: "women-receptionist-bangalore-850001001",
    title: "Female Receptionist",
    company: "Aura Wellness Clinic",
    city: "Bengaluru/Bangalore",
    salary: "Rs. 15,000 - Rs. 22,000 monthly",
    salaryMin: 15000,
    salaryMax: 22000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Back Office",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Good English",
    tag: "Women preferred",
    openings: 2,
    location: "Indiranagar, Bengaluru",
    interviewAddress: "Aura Wellness Clinic, Indiranagar, Bengaluru",
    description: "Aura Wellness Clinic is hiring a female receptionist to manage front desk, appointments, and client interactions in a professional wellness environment.",
    responsibilities: [
      "Greet clients and manage appointment bookings.",
      "Handle phone and email inquiries.",
      "Maintain front desk records and daily reports.",
    ],
    requirements: [
      "Pleasant personality and good communication.",
      "Basic computer knowledge.",
      "Freshers can apply.",
    ],
    benefits: ["Day shift only", "Health benefits", "Professional environment"],
  },
  {
    id: "women-customer-support-mumbai-850001002",
    title: "Customer Support Executive (Women)",
    company: "CareFirst Services",
    city: "Mumbai/Bombay",
    salary: "Rs. 18,000 - Rs. 28,000 monthly",
    salaryMin: 18000,
    salaryMax: 28000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 1,
    experience: "Any experience",
    english: "Good English",
    tag: "Women preferred",
    openings: 10,
    location: "Bandra, Mumbai",
    interviewAddress: "CareFirst Services, Bandra West, Mumbai",
    description: "CareFirst Services is hiring female customer support executives for day shift. Safe, professional workplace with women-friendly policies.",
    responsibilities: [
      "Handle customer queries via phone and chat.",
      "Resolve complaints and escalate when needed.",
      "Maintain call records and daily reports.",
    ],
    requirements: [
      "Good spoken English and Hindi.",
      "Basic computer skills.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Day shift only", "Cab facility", "Women-friendly workplace"],
  },
  {
    id: "women-wfh-telecaller-850001003",
    title: "Work from Home Telecaller (Women)",
    company: "HomeConnect BPO",
    city: "Remote",
    salary: "Rs. 12,000 - Rs. 20,000 monthly",
    salaryMin: 12000,
    salaryMax: 20000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Basic English",
    tag: "Women preferred",
    openings: 25,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "HomeConnect BPO is hiring women for work-from-home telecalling roles. Ideal for homemakers and women returning to work.",
    responsibilities: [
      "Make outbound calls to customers from home.",
      "Explain products and record call outcomes.",
      "Meet daily call targets.",
    ],
    requirements: [
      "Clear communication in Hindi or regional language.",
      "Smartphone or laptop with internet.",
      "Homemakers and freshers welcome.",
    ],
    benefits: ["Work from home", "Flexible hours", "Joining bonus"],
  },
  {
    id: "women-teacher-delhi-850001004",
    title: "Female Teacher / Educator",
    company: "Sunrise Public School",
    city: "New Delhi",
    salary: "Rs. 20,000 - Rs. 35,000 monthly",
    salaryMin: 20000,
    salaryMax: 35000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Customer Support",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Good English",
    tag: "Women preferred",
    openings: 5,
    location: "Rohini, New Delhi",
    interviewAddress: "Sunrise Public School, Rohini Sector 7, New Delhi",
    description: "Sunrise Public School is hiring female teachers for primary and middle school sections. Day shift with school holidays.",
    responsibilities: [
      "Teach assigned subjects to students as per curriculum.",
      "Prepare lesson plans and conduct assessments.",
      "Maintain student progress records.",
    ],
    requirements: [
      "B.Ed or equivalent teaching qualification.",
      "Good communication and classroom management skills.",
      "Freshers with teaching interest can apply.",
    ],
    benefits: ["School holidays", "PF benefits", "Stable career"],
  },
  {
    id: "women-beauty-advisor-chennai-850001005",
    title: "Beauty Advisor (Female)",
    company: "GlowUp Cosmetics",
    city: "Chennai",
    salary: "Rs. 14,000 - Rs. 22,000 monthly",
    salaryMin: 14000,
    salaryMax: 22000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Retail / Counter Sales",
    shift: "Day Shift",
    postedDaysAgo: 2,
    experience: "Any experience",
    english: "Basic English",
    tag: "Women preferred",
    openings: 8,
    location: "T Nagar, Chennai",
    interviewAddress: "GlowUp Cosmetics, T Nagar, Chennai",
    description: "GlowUp Cosmetics is hiring female beauty advisors to assist customers with product selection, demonstrations, and in-store sales.",
    responsibilities: [
      "Assist customers in choosing skincare and cosmetic products.",
      "Conduct product demonstrations and explain benefits.",
      "Achieve monthly sales targets.",
    ],
    requirements: [
      "Interest in beauty and cosmetics.",
      "Good communication in Tamil or English.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Product allowance", "Sales incentives", "Training provided"],
  },
  {
    id: "women-hr-recruiter-pune-850001006",
    title: "HR Recruiter (Female Preferred)",
    company: "PeopleFirst HR",
    city: "Pune",
    salary: "Rs. 18,000 - Rs. 30,000 monthly",
    salaryMin: 18000,
    salaryMax: 30000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Human Resource",
    shift: "Day Shift",
    postedDaysAgo: 4,
    experience: "Freshers only",
    english: "Good English",
    tag: "Women preferred",
    openings: 4,
    location: "Hinjewadi, Pune",
    interviewAddress: "PeopleFirst HR, Hinjewadi Phase 1, Pune",
    description: "PeopleFirst HR is hiring female HR recruiters to manage sourcing, screening, and onboarding for IT and non-IT clients.",
    responsibilities: [
      "Source candidates through job portals and LinkedIn.",
      "Conduct initial telephonic screening.",
      "Coordinate interview schedules and send offer letters.",
    ],
    requirements: [
      "MBA in HR or equivalent preferred.",
      "Good communication and organizational skills.",
      "Freshers can apply.",
    ],
    benefits: ["Day shift", "Health insurance", "Career growth"],
  },
  {
    id: "women-wfh-data-entry-850001007",
    title: "Work from Home Data Entry (Women)",
    company: "FlexWork Solutions",
    city: "Remote",
    salary: "Rs. 10,000 - Rs. 18,000 monthly",
    salaryMin: 10000,
    salaryMax: 18000,
    mode: "Work from Home",
    type: "Full Time",
    department: "Back Office",
    shift: "Flexible Shift",
    postedDaysAgo: 1,
    experience: "Freshers only",
    english: "Basic English",
    tag: "Women preferred",
    openings: 20,
    location: "Work from home",
    interviewAddress: "Online interview",
    description: "FlexWork Solutions is hiring women for work-from-home data entry roles. Ideal for homemakers and women seeking flexible employment.",
    responsibilities: [
      "Enter and verify data in company systems.",
      "Prepare daily reports and share with team lead.",
      "Maintain accuracy and meet daily targets.",
    ],
    requirements: [
      "Basic computer and typing skills.",
      "Laptop or desktop with internet.",
      "Homemakers and freshers welcome.",
    ],
    benefits: ["Work from home", "Flexible hours", "Fixed monthly salary"],
  },
  {
    id: "women-accounts-kolkata-850001008",
    title: "Accounts Executive (Female Preferred)",
    company: "Calcutta Finance House",
    city: "Kolkata/Calcutta",
    salary: "Rs. 16,000 - Rs. 26,000 monthly",
    salaryMin: 16000,
    salaryMax: 26000,
    mode: "Work from Office",
    type: "Full Time",
    department: "Accounts / Finance",
    shift: "Day Shift",
    postedDaysAgo: 3,
    experience: "Any experience",
    english: "Basic English",
    tag: "Women preferred",
    openings: 3,
    location: "Park Street, Kolkata",
    interviewAddress: "Calcutta Finance House, Park Street, Kolkata",
    description: "Calcutta Finance House is hiring female accounts executives for bookkeeping, invoicing, and financial reporting tasks.",
    responsibilities: [
      "Maintain daily accounts and ledger entries.",
      "Prepare GST invoices and bank reconciliation.",
      "Assist in monthly financial closing.",
    ],
    requirements: [
      "B.Com or equivalent qualification.",
      "Basic Tally knowledge preferred.",
      "Freshers and experienced candidates can apply.",
    ],
    benefits: ["Day shift", "PF benefits", "Safe workplace"],
  },];

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function getJobHref(job: Job) {
  return `/job/${slugify(job.city)}/${job.id}`;
}

export function getJobBySlug(slug: string) {
  return jobs.find((job) => job.id === slug);
}
